# Generated by Django 2.0.6 on 2020-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='10', max_length=1000000000000, null=True)),
                ('cP', models.CharField(default='2', max_length=1000000000000, null=True)),
                ('minC', models.CharField(default='2', max_length=1000000000000, null=True)),
                ('bsMargin', models.CharField(default='2', max_length=1000000000000, null=True)),
            ],
        ),
    ]
