# Generated by Django 2.0.6 on 2020-06-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='bsMargin',
            new_name='buysellMargin',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='cP',
            new_name='commissionPercentage',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='minC',
            new_name='minimumCommission',
        ),
    ]
