# Generated by Django 2.0.6 on 2020-06-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20200609_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='surcharge',
            field=models.CharField(default='2', max_length=1000000000000, null=True),
        ),
    ]
